### ISSUE TITLE
Script to parse NVD JSON file to extract the CVSSv2 and v3 Base score parameters

### ISSUE THREAD

**Issue by Crashedmind** [epss-sig/epss-interoperability#18]
**Description, Use Case and User Stories**
Script to parse NVD JSON files to extract the CVSSv2 and v3 Base score parameters to a CSV file.

These fields would be extracted:
                cvssV2Version = str('CVSSv' + x['impact']['baseMetricV2']['cvssV2']['version'])
                cvssV2AccessVector = str(x['impact']['baseMetricV2']['cvssV2']['accessVector'])
                cvssV2AccessComplexity = str(x['impact']['baseMetricV2']['cvssV2']['accessComplexity'])
                cvssV2Authentication = str(x['impact']['baseMetricV2']['cvssV2']['authentication'])
                cvssV2ConfidentialityImpact = str(x['impact']['baseMetricV2']['cvssV2']['confidentialityImpact'])
                cvssV2IntegrityImpact = str(x['impact']['baseMetricV2']['cvssV2']['integrityImpact'])
                cvssV2AvailabilityImpact = str(x['impact']['baseMetricV2']['cvssV2']['availabilityImpact'])
                cvssV2Score = float(x['impact']['baseMetricV2']['cvssV2']['baseScore'])
                cvssV2Severity = str(x['impact']['baseMetricV2']['severity'])
                cvssV3Version = str('CVSSv' + x['impact']['baseMetricV3']['cvssV3']['version'])
                cvssV3AttackVector = str(x['impact']['baseMetricV3']['cvssV3']['attackVector'])
                cvssV3AttackComplexity = str(x['impact']['baseMetricV3']['cvssV3']['attackComplexity'])
                cvssV3PrivilegesRequired = str(x['impact']['baseMetricV3']['cvssV3']['privilegesRequired'])
                cvssV3UserInteraction = str(x['impact']['baseMetricV3']['cvssV3']['userInteraction'])
                cvssV3Scope = str(x['impact']['baseMetricV3']['cvssV3']['scope'])
                cvssV3ConfidentialityImpact = str(x['impact']['baseMetricV3']['cvssV3']['confidentialityImpact'])
                cvssV3IntegrityImpact = str(x['impact']['baseMetricV3']['cvssV3']['integrityImpact'])
                cvssV3AvailabilityImpact = str(x['impact']['baseMetricV3']['cvssV3']['availabilityImpact'])
                cvssV3Score = float(x['impact']['baseMetricV3']['cvssV3']['baseScore'])
                cvssV3Severity = str(x['impact']['baseMetricV3']['cvssV3']['baseSeverity'])

The script would be open sourced and used as part of the EPSS Applied guide to replace the current QuickNdirty script I wrote that only does V3 https://github.com/epss-sig/epss-interoperability/tree/main/data_in/nvd)

**Definition of Ready**
(Assignee lists the things they need from the Requestor to be able to start work on this)

**Acceptance Criteria**
(Requestor lists the things they need the deliverable to be able to accept this from the Assignee)

**Additional context**

**Comment by jgamblin** [comment]
Jupyter notebook to pull this data is located here: 
https://gist.github.com/jgamblin/7a927997b1f1e35cc7f4f1788ee5eae1
